In [2]:
import numpy as np


In [22]:
#create array - from list
arr = np.array([1,2,3,4,5])
print(arr,type(arr), arr.shape)

arr2 = np.array([6,7,8,9,10 , "arpit"])
print(arr,type(arr), arr2.dtype, arr2.shape)

arr2D =np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
[1 2 3 4 5] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [38]:
#create np array with scratch
arr1= np.zeros((2,3), dtype="int64")#prefill
print(arr1,arr1.shape)

arr2= np.ones((2,3), dtype="int64")#prefill
print(arr2,arr2.shape)

arr3= np.full((2,3),100)#prefill with value
print(arr3,arr3.shape)


arr4= np.eye(3) #identity matrix
print(arr4,arr4.shape)

arr5= np.arange(0,11,2) #range element
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced array
print(arr6,arr6.shape)




[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [3]:
#properties
arr = np.array([1,2,3,4,5])

print(arr.shape) #dimensions = m x n
print(arr.size) #total ele
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(5,)
5
int64
1
[1. 2. 3. 4. 5.] float64


In [9]:
#operations on array

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened =  arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [14]:
#indexing 

arr = np.array([1,3,5,7,9])
print(arr[3])
print(arr[0])

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1[1][1])



7
1
5


In [16]:
#fancy indexing
arr = np.array([1,3,5,7,9])
idx = [0,1,2]

print(arr[idx])

[1 3 5]


In [23]:
#boolean indexing
arr = np.array([1,3,5,7,9])

print(arr[arr > 3 ])
print(arr[arr % 2 ==0 ])
print(arr[arr % 2 !=0 ])

[5 7 9]
[]
[1 3 5 7 9]


In [26]:
#slicing
arr = np.array([1,3,5,7,9])

print(arr[1:4]) #start , end , step

[3 5 7]


In [7]:
 # data types in numpy

arr = np.array([1,2,3,4,5])

print(arr,arr.dtype)



arr = np.array([1,2,3.5,4,5])

print(arr,arr.dtype)



arr = np.array([1,2,"hello",4,5])

print(arr,arr.dtype)


arr = np.array([3+5j])
print (arr,arr.dtype)

[1 2 3 4 5] int64
[1.  2.  3.5 4.  5. ] float64
['1' '2' 'hello' '4' '5'] <U21
[3.+5.j] complex128


In [20]:
#Multi Dimensional Arrays

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (arr2D)

print(np.sum(arr2D))

sum_of_column = np.sum(arr2D, axis = 0)
print(sum_of_column)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [33]:
#3D array

arr3D = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])
print (arr3D,arr3D.shape)

#indexing
print(arr3D[0,1,1], arr3D[1,1,0])

#slicing
print(arr3D[:,0,:]) #print first row from both   

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4 9
[[1 2]
 [7 8]]


In [38]:
#vectorization
arr = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])

print(arr ** 2)
print(arr + 5)
print(arr + arr2)

[ 1  9 25 49 81]
[ 6  8 10 12 14]
[ 3  7 11 15 19]


In [42]:
#broadcasting
arr = np.array([1,3,5,7,9])
arr2 = np.array([[1,3,5,7,9], [1,3,5,7,9]])

print(arr + arr2)
print(arr.shape, arr2.shape)


[[ 2  6 10 14 18]
 [ 2  6 10 14 18]]
(5,) (2, 5)


In [8]:
#normalize

arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr =(arr - mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [15]:
#mathematical fnx

#aggregation

arr = np.array([1,3,5,7,9])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

25
945
1
9
0
4
5.0
2.8284271247461903
5.0
8.0


In [18]:
# power fnx

arr = np.array([1,3,5,7,9])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  9 25 49 81]
[1.         1.73205081 2.23606798 2.64575131 3.        ]
[  1  27 125 343 729]


In [23]:
#log 

arr = np.array([1,3,5,7,9])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         1.09861229 1.60943791 1.94591015 2.19722458]
[0.         1.5849625  2.32192809 2.80735492 3.169925  ]
[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 8.10308393e+03]


In [28]:
#rounding
print(np.round(3.14))
print(np.round(3.94))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,3,5,7,3,5,7,9])
print(np.unique(arr))
print(np.sort(arr))


3.0
4.0
3.0
3.0
[1 3 5 7 9]
[1 3 3 5 5 7 7 9]
